plugins:
  hiveon_homepage_enabled:
    default: true
    client: true
  hiveon_homepage_img_url:
    default: 'https://simple-storage.sgp1.digitaloceanspaces.com/intro2.svg'
    client: true
  hiveon_homepage_header_title:
    default: 'Online community with'
    client: true
  hiveon_homepage_header_text:
    default: 'Swap tips and ideas with your peers to build community for your members, your company, and your career'
    client: true
